outputPath: '../../site/blog'
posts:
  - name: 'GettersAndSetters'
    title: 'A tale of getters and setters'
    date: '22/02/2018'
    description: 'A look at getters and setters in OO systems'
  - name: 'FileSystems'
    title: 'Stop working around your file system'
    date: '20/06/2018'
    description: 'Proposal for CodeDb, an alternative to storing code directly on your file system.'
