outputPath: '../../site/blog'
posts:
  - name: 'TestPost'
    title: 'My Test Post'
    date: '20/02/2018'
    description: 'This is a little bit of information about the test post.'
  - name: 'AnotherPost'
    title: 'Another Post'
    date: '21/02/2018'
    description: 'How about a little bit of information about another post.'
